// <auto-generated />
namespace Team1_Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class please : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(please));
        
        string IMigrationMetadata.Id
        {
            get { return "201611291805076_please"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
