// <auto-generated />
namespace Team1_Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sai122838am : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sai122838am));
        
        string IMigrationMetadata.Id
        {
            get { return "201612021438552_sai122838am"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
