// <auto-generated />
namespace Team1_Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testinground4on1120 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testinground4on1120));
        
        string IMigrationMetadata.Id
        {
            get { return "201611202135198_testing round 4 on 11-20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
